// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcpc-9HtcwAu81EqZh8KRMceb_bBLyiQ',
    appId: '1:901568455027:web:36906062ea5116a78f2506',
    messagingSenderId: '901568455027',
    projectId: 'eclinic-b59fd',
    authDomain: 'eclinic-b59fd.firebaseapp.com',
    storageBucket: 'eclinic-b59fd.appspot.com',
    measurementId: 'G-5T64DW0SKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD28AffQNADNEoB_MVbG-uWfm7kYBB4c-c',
    appId: '1:901568455027:android:3a240ecce22e791e8f2506',
    messagingSenderId: '901568455027',
    projectId: 'eclinic-b59fd',
    storageBucket: 'eclinic-b59fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIt56U9bi83fUYaDEu5ZIT8gVDXxCYBKk',
    appId: '1:901568455027:ios:e7491aff3e4740ff8f2506',
    messagingSenderId: '901568455027',
    projectId: 'eclinic-b59fd',
    storageBucket: 'eclinic-b59fd.appspot.com',
    iosBundleId: 'com.example.medisafe',
  );
}
